name: 问题反馈
description: 问题反馈
labels: ["Bug"]
title: "[问题反馈] "
body:
  - type: textarea
    attributes:
      label: 复现步骤
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 预期行为
      placeholder: "正常应该发生什么"
    validations:
      required: true

  - type: textarea
    attributes:
      label: 实际行为
      placeholder: "实际发生了什么"
    validations:
      required: true

  - type: input
    attributes:
      label: 模块版本
      placeholder: "如: 1.0.0(218)"
    validations:
      required: true

  - type: input
    attributes:
      label: 微信版本
      placeholder: "如: 8.0.45(2520)"
    validations:
      required: true

  - type: input
    attributes:
      label: 你的Xposed框架
      placeholder: "如: LSPosed(Zygisk) 1.9.2(7024)"
    validations:
      required: true

  - type: input
    attributes:
      label: 你使用的安卓系统版本
      placeholder: "如: 12"
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 版本和其他要求
      options:
        - label: 我在 [Issue](https://github.com/HdShare/WAuxiliary_Public/issues) 没有发现相同问题
          required: true
        - label: 我已知晓不按照模板提供的指示进行填写, 则我的 Issue 可能会被无条件删除
          required: true

  - type: textarea
    attributes:
      label: 补充说明(可选)
